name: restaged
description: A Furniture Sharing App That Makes Staging Easy.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1 # Application versioning 

environment:
  sdk: '>=2.19.2 <3.0.0'

dependencies:
  flutter:
    sdk: flutter
  auto_route: ^5.0.4 # declarative routing solution
  cupertino_icons: ^1.0.2 # Cupertino Icons
  dio: ^5.0.1 # http package
  logger: ^1.2.2 # application logger
  pretty_dio_logger: ^1.3.1 # network logger
  rx_shared_preferences: ^3.0.0 # a stream wrapper

dev_dependencies:
  assets_gen: ^1.5.0 # assets handler
  auto_route_generator: ^5.0.3 # route generator
  build_runner: ^2.3.3 # builder
  json_annotation: ^4.8.0 # json code generator
  json_serializable: ^6.6.1 # json serializer

  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0 # app linter

flutter: #Flutter packages.
  uses-material-design: true #include material font

