// GENERATED CODE - DO NOT MODIFY BY HAND

// **************************************************************************
// Total assets: 62.
// Generated by https://pub.dev/packages/assets_gen.
// **************************************************************************

// ignore_for_file: constant_identifier_names,non_constant_identifier_names,lines_longer_than_80_chars
class Assets {
  static const String package = 'restaged';

  static const String assets_svg_404_error_svg = 'assets/svg/404_error.svg';
  static const String restaged$assets_svg_404_error_svg = 'packages/restaged/assets/svg/404_error.svg';

  static const String assets_svg_auth_apple_svg = 'assets/svg/auth_apple.svg';
  static const String restaged$assets_svg_auth_apple_svg = 'packages/restaged/assets/svg/auth_apple.svg';

  static const String assets_svg_auth_chage_password_svg = 'assets/svg/auth_chage_password.svg';
  static const String restaged$assets_svg_auth_chage_password_svg = 'packages/restaged/assets/svg/auth_chage_password.svg';

  static const String assets_svg_auth_facebook_svg = 'assets/svg/auth_facebook.svg';
  static const String restaged$assets_svg_auth_facebook_svg = 'packages/restaged/assets/svg/auth_facebook.svg';

  static const String assets_svg_auth_google_svg = 'assets/svg/auth_google.svg';
  static const String restaged$assets_svg_auth_google_svg = 'packages/restaged/assets/svg/auth_google.svg';

  static const String assets_svg_auth_hide_password_svg = 'assets/svg/auth_hide_password.svg';
  static const String restaged$assets_svg_auth_hide_password_svg = 'packages/restaged/assets/svg/auth_hide_password.svg';

  static const String assets_svg_auth_lock_svg = 'assets/svg/auth_lock.svg';
  static const String restaged$assets_svg_auth_lock_svg = 'packages/restaged/assets/svg/auth_lock.svg';

  static const String assets_svg_auth_mail_svg = 'assets/svg/auth_mail.svg';
  static const String restaged$assets_svg_auth_mail_svg = 'packages/restaged/assets/svg/auth_mail.svg';

  static const String assets_svg_auth_rest_passowrd_mail_svg = 'assets/svg/auth_rest_passowrd_mail.svg';
  static const String restaged$assets_svg_auth_rest_passowrd_mail_svg = 'packages/restaged/assets/svg/auth_rest_passowrd_mail.svg';

  static const String assets_svg_auth_rest_password_forget_svg = 'assets/svg/auth_rest_password_forget.svg';
  static const String restaged$assets_svg_auth_rest_password_forget_svg = 'packages/restaged/assets/svg/auth_rest_password_forget.svg';

  static const String assets_svg_auth_show_password_svg = 'assets/svg/auth_show_password.svg';
  static const String restaged$assets_svg_auth_show_password_svg = 'packages/restaged/assets/svg/auth_show_password.svg';

  static const String assets_svg_auth_user_tif_svg = 'assets/svg/auth_user.tif.svg';
  static const String restaged$assets_svg_auth_user_tif_svg = 'packages/restaged/assets/svg/auth_user.tif.svg';

  static const String assets_svg_card_details_depth_svg = 'assets/svg/card_details_depth.svg';
  static const String restaged$assets_svg_card_details_depth_svg = 'packages/restaged/assets/svg/card_details_depth.svg';

  static const String assets_svg_card_details_handsahke_white_svg = 'assets/svg/card_details_handsahke_white.svg';
  static const String restaged$assets_svg_card_details_handsahke_white_svg = 'packages/restaged/assets/svg/card_details_handsahke_white.svg';

  static const String assets_svg_card_details_handshake_svg_green_svg = 'assets/svg/card_details_handshake.svg_green.svg';
  static const String restaged$assets_svg_card_details_handshake_svg_green_svg = 'packages/restaged/assets/svg/card_details_handshake.svg_green.svg';

  static const String assets_svg_card_details_height_svg = 'assets/svg/card_details_height.svg';
  static const String restaged$assets_svg_card_details_height_svg = 'packages/restaged/assets/svg/card_details_height.svg';

  static const String assets_svg_card_details_location_svg = 'assets/svg/card_details_location.svg';
  static const String restaged$assets_svg_card_details_location_svg = 'packages/restaged/assets/svg/card_details_location.svg';

  static const String assets_svg_card_details_location_green_svg = 'assets/svg/card_details_location_green.svg';
  static const String restaged$assets_svg_card_details_location_green_svg = 'packages/restaged/assets/svg/card_details_location_green.svg';

  static const String assets_svg_card_details_mail_green_svg = 'assets/svg/card_details_mail_green.svg';
  static const String restaged$assets_svg_card_details_mail_green_svg = 'packages/restaged/assets/svg/card_details_mail_green.svg';

  static const String assets_svg_card_details_phone_svg = 'assets/svg/card_details_phone.svg';
  static const String restaged$assets_svg_card_details_phone_svg = 'packages/restaged/assets/svg/card_details_phone.svg';

  static const String assets_svg_card_details_phone_green_svg = 'assets/svg/card_details_phone_green.svg';
  static const String restaged$assets_svg_card_details_phone_green_svg = 'packages/restaged/assets/svg/card_details_phone_green.svg';

  static const String assets_svg_card_details_report_svg = 'assets/svg/card_details_report.svg';
  static const String restaged$assets_svg_card_details_report_svg = 'packages/restaged/assets/svg/card_details_report.svg';

  static const String assets_svg_card_details_star_green_svg = 'assets/svg/card_details_star_green.svg';
  static const String restaged$assets_svg_card_details_star_green_svg = 'packages/restaged/assets/svg/card_details_star_green.svg';

  static const String assets_svg_card_details_star_white_svg = 'assets/svg/card_details_star_white.svg';
  static const String restaged$assets_svg_card_details_star_white_svg = 'packages/restaged/assets/svg/card_details_star_white.svg';

  static const String assets_svg_card_details_trash_svg = 'assets/svg/card_details_trash.svg';
  static const String restaged$assets_svg_card_details_trash_svg = 'packages/restaged/assets/svg/card_details_trash.svg';

  static const String assets_svg_card_details_whishlist_svg = 'assets/svg/card_details_whishlist.svg';
  static const String restaged$assets_svg_card_details_whishlist_svg = 'packages/restaged/assets/svg/card_details_whishlist.svg';

  static const String assets_svg_card_details_width_svg = 'assets/svg/card_details_width.svg';
  static const String restaged$assets_svg_card_details_width_svg = 'packages/restaged/assets/svg/card_details_width.svg';

  static const String assets_svg_filters_accessories_svg = 'assets/svg/filters_accessories.svg';
  static const String restaged$assets_svg_filters_accessories_svg = 'packages/restaged/assets/svg/filters_accessories.svg';

  static const String assets_svg_filters_beds_svg = 'assets/svg/filters_beds.svg';
  static const String restaged$assets_svg_filters_beds_svg = 'packages/restaged/assets/svg/filters_beds.svg';

  static const String assets_svg_filters_couches_and__sofas_svg = 'assets/svg/filters_couches_and _sofas.svg';
  static const String restaged$assets_svg_filters_couches_and__sofas_svg = 'packages/restaged/assets/svg/filters_couches_and _sofas.svg';

  static const String assets_svg_filters_set_svg = 'assets/svg/filters_set.svg';
  static const String restaged$assets_svg_filters_set_svg = 'packages/restaged/assets/svg/filters_set.svg';

  static const String assets_svg_filters_storage_svg = 'assets/svg/filters_storage.svg';
  static const String restaged$assets_svg_filters_storage_svg = 'packages/restaged/assets/svg/filters_storage.svg';

  static const String assets_svg_filters_tabels_and_chairs_svg = 'assets/svg/filters_tabels_and_chairs.svg';
  static const String restaged$assets_svg_filters_tabels_and_chairs_svg = 'packages/restaged/assets/svg/filters_tabels_and_chairs.svg';

  static const String assets_svg_logo_horizontal_svg = 'assets/svg/logo_horizontal.svg';
  static const String restaged$assets_svg_logo_horizontal_svg = 'packages/restaged/assets/svg/logo_horizontal.svg';

  static const String assets_svg_logo_vertical_svg = 'assets/svg/logo_vertical.svg';
  static const String restaged$assets_svg_logo_vertical_svg = 'packages/restaged/assets/svg/logo_vertical.svg';

  static const String assets_svg_navigation_back_chevron_svg = 'assets/svg/navigation_back_chevron.svg';
  static const String restaged$assets_svg_navigation_back_chevron_svg = 'packages/restaged/assets/svg/navigation_back_chevron.svg';

  static const String assets_svg_panel_cart_svg = 'assets/svg/panel_cart.svg';
  static const String restaged$assets_svg_panel_cart_svg = 'packages/restaged/assets/svg/panel_cart.svg';

  static const String assets_svg_panel_change_password_svg = 'assets/svg/panel_change_password.svg';
  static const String restaged$assets_svg_panel_change_password_svg = 'packages/restaged/assets/svg/panel_change_password.svg';

  static const String assets_svg_panel_happy_lamp_svg = 'assets/svg/panel_happy_lamp.svg';
  static const String restaged$assets_svg_panel_happy_lamp_svg = 'packages/restaged/assets/svg/panel_happy_lamp.svg';

  static const String assets_svg_panel_have_hand_svg = 'assets/svg/panel_have_hand.svg';
  static const String restaged$assets_svg_panel_have_hand_svg = 'packages/restaged/assets/svg/panel_have_hand.svg';

  static const String assets_svg_panel_lazy_lamp_svg = 'assets/svg/panel_lazy_lamp.svg';
  static const String restaged$assets_svg_panel_lazy_lamp_svg = 'packages/restaged/assets/svg/panel_lazy_lamp.svg';

  static const String assets_svg_panel_logout_svg = 'assets/svg/panel_logout.svg';
  static const String restaged$assets_svg_panel_logout_svg = 'packages/restaged/assets/svg/panel_logout.svg';

  static const String assets_svg_panel_my_cards_svg = 'assets/svg/panel_my_cards.svg';
  static const String restaged$assets_svg_panel_my_cards_svg = 'packages/restaged/assets/svg/panel_my_cards.svg';

  static const String assets_svg_panel_non_user_svg = 'assets/svg/panel_non_user.svg';
  static const String restaged$assets_svg_panel_non_user_svg = 'packages/restaged/assets/svg/panel_non_user.svg';

  static const String assets_svg_panel_pending_orders_svg = 'assets/svg/panel_pending_orders.svg';
  static const String restaged$assets_svg_panel_pending_orders_svg = 'packages/restaged/assets/svg/panel_pending_orders.svg';

  static const String assets_svg_panel_user_svg = 'assets/svg/panel_user.svg';
  static const String restaged$assets_svg_panel_user_svg = 'packages/restaged/assets/svg/panel_user.svg';

  static const String assets_svg_profile_edit_svg = 'assets/svg/profile_edit.svg';
  static const String restaged$assets_svg_profile_edit_svg = 'packages/restaged/assets/svg/profile_edit.svg';

  static const String assets_svg_profile_info_svg = 'assets/svg/profile_info.svg';
  static const String restaged$assets_svg_profile_info_svg = 'packages/restaged/assets/svg/profile_info.svg';

  static const String assets_svg_profile_tick_svg = 'assets/svg/profile_tick.svg';
  static const String restaged$assets_svg_profile_tick_svg = 'packages/restaged/assets/svg/profile_tick.svg';

  static const String assets_svg_profile_x_svg = 'assets/svg/profile_x.svg';
  static const String restaged$assets_svg_profile_x_svg = 'packages/restaged/assets/svg/profile_x.svg';

  static const String assets_svg_restager_uncel_sam_svg = 'assets/svg/restager_uncel_sam.svg';
  static const String restaged$assets_svg_restager_uncel_sam_svg = 'packages/restaged/assets/svg/restager_uncel_sam.svg';

  static const String assets_svg_search_calendar_svg = 'assets/svg/search_calendar.svg';
  static const String restaged$assets_svg_search_calendar_svg = 'packages/restaged/assets/svg/search_calendar.svg';

  static const String assets_svg_search_close_svg = 'assets/svg/search_close.svg';
  static const String restaged$assets_svg_search_close_svg = 'packages/restaged/assets/svg/search_close.svg';

  static const String assets_svg_search_icon_svg = 'assets/svg/search_icon.svg';
  static const String restaged$assets_svg_search_icon_svg = 'packages/restaged/assets/svg/search_icon.svg';

  static const String assets_svg_search_outdoor_svg = 'assets/svg/search_outdoor.svg';
  static const String restaged$assets_svg_search_outdoor_svg = 'packages/restaged/assets/svg/search_outdoor.svg';

  static const String assets_svg_serach_filter_svg = 'assets/svg/serach_filter.svg';
  static const String restaged$assets_svg_serach_filter_svg = 'packages/restaged/assets/svg/serach_filter.svg';

  static const String assets_svg_tabar_add_svg = 'assets/svg/tabar_add.svg';
  static const String restaged$assets_svg_tabar_add_svg = 'packages/restaged/assets/svg/tabar_add.svg';

  static const String assets_svg_tabar_cart_svg = 'assets/svg/tabar_cart.svg';
  static const String restaged$assets_svg_tabar_cart_svg = 'packages/restaged/assets/svg/tabar_cart.svg';

  static const String assets_svg_tabar_home_svg = 'assets/svg/tabar_home.svg';
  static const String restaged$assets_svg_tabar_home_svg = 'packages/restaged/assets/svg/tabar_home.svg';

  static const String assets_svg_tabar_orders_svg = 'assets/svg/tabar_orders.svg';
  static const String restaged$assets_svg_tabar_orders_svg = 'packages/restaged/assets/svg/tabar_orders.svg';

  static const String assets_svg_tabar_panel_svg = 'assets/svg/tabar_panel.svg';
  static const String restaged$assets_svg_tabar_panel_svg = 'packages/restaged/assets/svg/tabar_panel.svg';

  static const String assets_svg_welcome_carousel_svg = 'assets/svg/welcome_carousel.svg';
  static const String restaged$assets_svg_welcome_carousel_svg = 'packages/restaged/assets/svg/welcome_carousel.svg';
}
